# Generated by Django 5.0.3 on 2024-04-07 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_rename_nome_mae_todo_nome_mae_1"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="nome_mae_1",
            new_name="nome_mae",
        ),
    ]
