# Generated by Django 5.0.3 on 2024-04-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0003_rename_nome_mae_1_todo_nome_mae"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="deadline",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="todo",
            name="dt_inicio",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="todo",
            name="finished_at",
            field=models.DateField(null=True),
        ),
    ]
